# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Image fusion with guided filtering
author: Gabriel Belouze & Raphaël Rozenberg
logo: logo.png
exclude_patterns : [
  _build, .DS_Store, "**.ipynb_checkpoints",
  "*.ipynb",
  # "experiments.md",
  # "guided_filter.md",
  # "image_fusion.md",
  # "load_data.md",
  # "own_data.md",
  "rendu*"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  timeout: 100
  execute_notebooks: cache
  exclude_patterns:
    - 'rendu.*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: rapport.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/gbelouze/mva-imagerie-numerique  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  favicon: "favicon.ico"

# Launch button settings
launch_buttons:
  binderhub_url             : ""
